### ISSUE TITLE
Error when trying to break a display sign

### ISSUE THREAD

**Issue by TheBusyBiscuit** [Slimefun/SensibleToolbox#10]
## :round_pushpin: Description (REQUIRED)

When breaking the display sign of a machine the server halts for a bit and spits out an error.
You do actually get the sign but the error shouldn't happen really.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Left click a machine with a sign to place a display sign
2. Break the sign
3. Watch the error pop up

## :bulb: Expected behavior (REQUIRED)

I expected no error to open and no pause

## :scroll: Server Log

Here's the error that generated:
https://pastebin.com/7QMX4zZe

## :compass: Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper (git-204)
 - Minecraft Version: 1.16.3
 - SensibleToolbox Version: DEV - 1 @ b0ab4a746c79db37a6f8077cb73bb5906fc72488

**Comment by michel-zimmer** [comment]
I'd like to give it a shot. Please assign the issue to me, thanks!

**Comment by TheBusyBiscuit** [comment]
@michel-zimmer Sure thing! Thanks for your interest :)
I'm looking forward to it!

**Comment by michel-zimmer** [comment]
So, it looks like there are 2-3 ways to fix this.
As stated in the exception the problem is in `io/github/thebusybiscuit/sensibletoolbox/listeners/GeneralListener.java:246`:
`org.bukkit.material.Sign cannot be cast to class org.bukkit.block.data.type.WallSign`.
The BlockBreakEvent contains a Sign, but in the code it is assumed that it's always a `WallSign`.

In theory this should be fine because in line 245 is a check, that should only let `WallSign`s through.
This check would be one point where this could be fixed because currently it let's plain `Sign`s though, too.

The second way to fix this would be to not cast it to a `WallSign`, but instead just cast it to a `Sign` or maybe even just a `Directional`, because `Directional` (implemented by `Sign` and by `WallSign`) contains the method `getFacing`, which is the only required access to that object (line 247 and 251).

The third way would be to remove the entire `onLabelSignBroken` method. The only thing that it actually does as far as I can tell is calling `detachLabelSign` on the block where the label is attached to. But that method explicitly state `Don't call this method directly; it is automatically called when a label sign attached the block is broken.` in the JavaDoc.

Any opinions on this?

Also, what would be proper testing of my changes? Something along the lines of starting a server, adding only this plugin and then braking all combinations of signs, wall signs and blocks where they are attached to, right?

**Comment by TheBusyBiscuit** [comment]
@michel-zimmer So I had a look at the code and noticed some things

> In theory this should be fine because in line 245 is a check, that should only let WallSigns through.
This check would be one point where this could be fixed because currently it let's plain Signs though, too.

The `Tag.WALL_SIGNS` will only let Wall Signs through, this is guaranteed by Minecraft's internal code and nothing we would need to worry about, so the issue will be further down the line. And this only working for Wall Signs is actually the right behaviour.

> The second way to fix this would be to not cast it to a WallSign, but instead just cast it to a Sign or maybe even just a Directional, because Directional (implemented by Sign and by WallSign) contains the method getFacing, which is the only used method of that object (line 247 and 251).

Whether you call it to `Directional` or `WallSign` doesn't matter really. Both extend `BlockData` and by looking at the docs about `BlockState#getData()` I noticed that the return type is actually a `MaterialData`. So the "data" returned here is a different class called "Sign" (extending MaterialData), however we were expecting a class called "WallSign" (extending **Block**Data).
So that's where this class casting mistake probably comes from.
So the actual solution to this would probably be to call `.getBlockData()` instead of `.getData()`. This will give us the object we are looking for and then we can proceed to cast it. Also, as `.getState()` is very slow since it creates a snapshot of the `BlockState`, we can omit this and call `Block#getBlockData()` directly. I think that would fix the issue.

> The third way would be to remove the entire onLabelSignBroken method. The only thing that it actually does as far as I can tell is calling detachLabelSign on the block where the label is attached to. But that method states Don't call this method directly; it is automatically called when a label sign attached the block is broken. in the JavaDoc explicitly.

I am not too familiar with this codebase myself but I would expect for this to be "the automatically handled" approach the docs refer to. Since both is internal code.

> Also, what would be proper testing of my changes? Something along the lines of starting a server, adding only this plugin and then braking all combinations of signs, wall signs and blocks where they are attached to, right?

Well, we haven't rolled out Unit tests for SensibleToolbox yet, so the best (or only) way to test it would be to set up a server, add the plugin, start the server and try things out like you described.

**Comment by michel-zimmer** [comment]
> @michel-zimmer So I had a look at the code and noticed some things
> 
> > In theory this should be fine because in line 245 is a check, that should only let WallSigns through.
> > This check would be one point where this could be fixed because currently it let's plain Signs though, too.
> 
> The `Tag.WALL_SIGNS` will only let Wall Signs through, this is guaranteed by Minecraft's internal code and nothing we would need to worry about, so the issue will be further down the line. And this only working for Wall Signs is actually the right behaviour.

OK, good to know :+1: 

> > The second way to fix this would be to not cast it to a WallSign, but instead just cast it to a Sign or maybe even just a Directional, because Directional (implemented by Sign and by WallSign) contains the method getFacing, which is the only used method of that object (line 247 and 251).
> 
> Whether you call it to `Directional` or `WallSign` doesn't matter really. Both extend `BlockData` and by looking at the docs about `BlockState#getData()` I noticed that the return type is actually a `MaterialData`. So the "data" returned here is a different class called "Sign" (extending MaterialData), however we were expecting a class called "WallSign" (extending **Block**Data).
> So that's where this class casting mistake probably comes from.
> So the actual solution to this would probably be to call `.getBlockData()` instead of `.getData()`. This will give us the object we are looking for and then we can proceed to cast it. Also, as `.getState()` is very slow since it creates a snapshot of the `BlockState`, we can omit this and call `Block#getBlockData()` directly. I think that would fix the issue.

You are right. I don't understand it completely, but using `getBlockData` solves the problem. Somehow the extra turnaround via `getState` + `getData` only returns a `Sign`, but using `getBlockData` returns the proper `WallSign`.

I've tested this and it works. (PR follows)

> > The third way would be to remove the entire onLabelSignBroken method. The only thing that it actually does as far as I can tell is calling detachLabelSign on the block where the label is attached to. But that method states Don't call this method directly; it is automatically called when a label sign attached the block is broken. in the JavaDoc explicitly.
> 
> I am not too familiar with this codebase myself but I would expect for this to be "the automatically handled" approach the docs refer to. Since both is internal code.

You are right, somehow I though that `detachLabelSign` was from another `jar`, but of course, it's from this project, too.

> > Also, what would be proper testing of my changes? Something along the lines of starting a server, adding only this plugin and then braking all combinations of signs, wall signs and blocks where they are attached to, right?
> 
> Well, we haven't rolled out Unit tests for SensibleToolbox yet, so the best (or only) way to test it would be to set up a server, add the plugin, start the server and try things out like you described.

:+1:

**Comment by michel-zimmer** [comment]
Same problem for the `SignChangedEvent` btw.:

```txt
[20:31:04 ERROR]: Could not pass event SignChangeEvent to SensibleToolbox vUNOFFICIAL
java.lang.ClassCastException: org.bukkit.material.Sign cannot be cast to org.bukkit.block.data.type.WallSign
	at io.github.thebusybiscuit.sensibletoolbox.listeners.GeneralListener.onSignChange(GeneralListener.java:224) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor14.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-209]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-209]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-209]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-209]
	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2686) ~[patched_1.16.3.jar:git-Paper-209]
	at net.minecraft.server.v1_16_R2.PacketPlayInUpdateSign.a(SourceFile:41) ~[patched_1.16.3.jar:git-Paper-209]
	at net.minecraft.server.v1_16_R2.PacketPlayInUpdateSign.a(SourceFile:9) ~[patched_1.16.3.jar:git-Paper-209]
	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-209]
	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-209]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-209]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-209]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-209]
	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-209]
	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-209]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.3.jar:git-Paper-209]
	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1264) ~[patched_1.16.3.jar:git-Paper-209]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-209]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-209]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
```

**Comment by TheBusyBiscuit** [comment]
> Same problem for the `SignChangedEvent` btw.:

Ahh, please use pastebin XD
And oh, feel free to apply the same fix there too if you want, or make a seperate PR for it, that's entirely your decision.

>You are right. I don't understand it completely, but using getBlockData solves the problem. Somehow the extra turnaround via getState + getData only returns a Sign, but using getBlockData returns the proper WallSign.

Well `getState()` + `getData()` returns the **Material**Data, which is a class called "Sign", however `getBlockData()` returns the **Block**Data which can either be `Sign` or `WallSign`, whereas this `Sign` is a different class than the `MaterialData` variant of `Sign`.
The `MaterialData` classes were the old way of approaching things like that - given the age of this project, the error probably stems from that era too - and they were replaced by the new **Block**Data classes, which unfortunately share a similar if not equal naming convention, it can easily lead to mix-ups and confusions like this.

**Comment by michel-zimmer** [comment]
> pastebin

Will do next time (switched to a spoiler tag for now)

> And oh, feel free to apply the same fix there too if you want, or make a seperate PR for it, that's entirely your decision.

Done ( as you've already seen apparently :smile: )

> similar if not equal naming convention

Ah, yes, I see it now. (Never worked with the Bukkit API before.) Thanks for the explanation :+1:

**Comment by TheBusyBiscuit** [comment]
> Ah, yes, I see it now. (Never worked with the Bukkit API before.) Thanks for the explanation 👍

You're welcome. Pretty awesome though if you never worked with this API before!
I hope this was a fun experience for you then! :D

**Comment by michel-zimmer** [comment]
Yes, it was. I like hunting bugs :man_shrugging:
