### ISSUE TITLE
Sensible toolbox fails to load - 1.16.5 - rc 27

### ISSUE THREAD

**Issue by mrcoffee1026** [Slimefun/SensibleToolbox#103]
## :round_pushpin: Description (REQUIRED)

Sensible toolbox fails to load, now logs error:
java.lang.ClassNotFoundException: me.mrCookieSlime.Slimefun.Objects.SlimefunItem.SlimefunItem

## :scroll: Server Log

https://pastebin.com/yUHLVkwN

## :compass: Environment (REQUIRED)

This Server uses the following setup of Slimefun:
Paper git-Paper-788 (MC: 1.16.5)
Slimefun DEV - 968 (git 79c6c139)
Metrics-Module #25
Java 16

Installed Addons: (35)
  ExtraTools vDEV - 29 (git 83f6db7f)
  FoxyMachines vDEV - 51 (git 3493db25)
  SlimefunOreChunks vDEV - 15 (git 2520cb23)
  SensibleToolbox vDEV - 45 (git dbcee02b)
  DynaTech vDEV - 133 (git f1901252)
  ExtraGear vDEV - 13 (git c62047e2)
  CMILib v1.0.3.9
  InfinityExpansion vDEV - 123 (git f5f22167)
  ElectricSpawners vDEV - 23 (git 6ec96773)
  SFCalc vDEV - 36 (git 74973a41)
  ExtraHeads vDEV - 22 (git 35688aa3)
  MobCapturer vDEV - 17 (git c21b00a5)
  SlimyTreeTaps vDEV - 20 (git 963f0383)
  PrivateStorage vDEV - 18 (git 5832db21)
  FlowerPower vDEV - 5 (git 9772d319)
  SlimeTinker vDEV - 35 (git 5e4c1783)
  Galactifun vDEV - 10 (git 35f97ac1)
  TranscEndence vDEV - 35 (git b29a1a49)
  CMI v9.0.4.1
  FluffyMachines vDEV - 90 (git b36089e8)
  ChestTerminal vDEV - 44 (git 3115957d)
  DyedBackpacks vDEV - 17 (git 8b329e96)
  SoundMuffler vDEV - 22 (git 37411b6c)
  AlchimiaVitae vDEV - 12 (git d27baab4)
  SlimefunWarfare vDEV - 65 (git 0937c8d6)
  HotbarPets vDEV - 38 (git fa6c871d)
  EcoPower vDEV - 5 (git 5c1ecd68)
  SlimefunLuckyBlocks vDEV - 36 (git 60f0c8dc)
  ExoticGarden vDEV - 77 (git a2c4b6d3)
  Liquid vDEV - 13 (git 6b71d3b3)
  LiteXpansion vDEV - 155 (git 574d551a)
  SimpleUtils vDEV - 14 (git 4b1259c7)
  SoulJars vDEV - 23 (git b8358a1f)
  PotionExpansion vDEV - 5 (git e2cfcd8a)
  SlimyRepair vDEV - 4 (git 790c41cb)

**Comment by Sefiraat** [comment]
Slimefun RC27+ introduced breaking changes that STB is not quite yet ready for. My understanding is this is awaiting some changes in Dough before this will be fully fixed

**Comment by TheBusyBiscuit** [comment]
Fixed via #104 and in an upcoming build (probably tomorrow)
