### ISSUE TITLE
Spamming error in console while crafting

### ISSUE THREAD

**Issue by Volgeop** [Slimefun/SensibleToolbox#18]
## :round_pushpin: Description (REQUIRED)

Error in console while crafting in crafting table. Instantly spamming.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Upload plugin
2. Open crafting table
3. Place there anything, for ex. wood
4. Don't craft new item, just grab the old wood and... in console will pop up error

## :bulb: Expected behavior (REQUIRED)

This shouldn't spam into console... when you just place item to crafting table and then hold it again.

## :scroll: Server Log

https://pastebin.com/sGX8xVhs

## :compass: Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper
 - Minecraft Version: 1.16.3
 - SensibleToolbox Version: DEV 6
- CSCoreLib: 91
- Slimefun: 683
PS: Tested just with these 3 plugins.

**Comment by IAmSorryArt** [comment]
I'll do it!

**Comment by TheBusyBiscuit** [comment]
Uuuh awesome, looking forward to that :D
