### ISSUE TITLE
Seperate SQL statements into their own .sql files

### ISSUE THREAD

**Issue by TheBusyBiscuit** [Slimefun/SensibleToolbox#32]
## :round_pushpin: Description (REQUIRED)

Right now the classes [DBUpdaterTask.java](https://github.com/Slimefun/SensibleToolbox/blob/master/src/main/java/io/github/thebusybiscuit/sensibletoolbox/core/storage/DBUpdaterTask.java) and [LocationManager.java](https://github.com/Slimefun/SensibleToolbox/blob/master/src/main/java/io/github/thebusybiscuit/sensibletoolbox/core/storage/LocationManager.java) contain SQL statements in them as strings.

I would like to seperate these into their own dedicated .sql files and load them at runtime, this way it will be easier for us to edit these queries later down the line.

**Comment by idodin** [comment]
Hi - I'd be interested in helping out with this. Is there an ideal directory structure you'd like to store the .sql files in?

**Comment by TheBusyBiscuit** [comment]
Well, as the files are required to be available at runtime, they should go into the `src/main/resources` directory, so my suggestion would be something like `src/main/resources/sql`.
This new directory might also be needed to be added as a resource entry in the `pom.xml` then.

But yeah that's awesome, thanks :heart:
I went ahead and assigned you to this issue, let me know if you have any more questions.
