### ISSUE TITLE
Infernal dusts - double names

### ISSUE THREAD

**Issue by bobhenl** [Slimefun/SensibleToolbox#74]
## :round_pushpin: Description (REQUIRED)

Hi, when players kill blazes they get sometimes different types of internal dust (with different nbt probably). Then they cannot be stacked.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

Kill blazes and you will probably get these two types of infernal dust.

## :bulb: Expected behavior (REQUIRED)

Just one infernal dust item.

## :scroll: Screenshots

![image](https://user-images.githubusercontent.com/18662086/113423077-264c1b00-93ce-11eb-8904-4c0b74b16d25.png)
![image](https://user-images.githubusercontent.com/18662086/113423079-277d4800-93ce-11eb-9904-f9c0f70234de.png)
![image](https://user-images.githubusercontent.com/18662086/113423080-2815de80-93ce-11eb-88b8-f585b83cca46.png)
![image](https://user-images.githubusercontent.com/18662086/113423083-29470b80-93ce-11eb-813b-0bfa19294cc1.png)

## :compass: Environment (REQUIRED)

 - Server Software (Spigot/Paper): Purpur
 - Minecraft Version: 1.16.5
 - SensibleToolbox Version: 39

**Comment by TeamOah** [comment]
Oh yea, this is a real hassle, if you have a blaze farm it really clogs the system up having both stupid dusts dropping.
